### ISSUE TITLE
Minor correction to generated LUKS partition name

### ISSUE THREAD

**Issue by Agh42** [schm1d/AwesomeArchLinux#1]
Thank you very much for this excellent installation script! One minor correction I had to make while installing archlinux-2023.06.01-x86_64.iso was that the LUKS partition name was generated as `nvme0n13` for the commands while in reality it had to be `nvme0n1p3`.

To change that I simply edited `archlinux.sh` with vim and ran this replacement

```
:%s/"3"/"p3"/g
```

**Comment by schm1d** [comment]
> Thank you very much for this excellent installation script! One minor correction I had to make while installing archlinux-2023.06.01-x86_64.iso was that the LUKS partition name was generated as `nvme0n13` for the commands while in reality it had to be `nvme0n1p3`.
> 
> To change that I simply edited `archlinux.sh` with vim and ran this replacement
> 
> ```
> :%s/"3"/"p3"/g
> ```

Hi, and thank you for using my script. Could you point me to the line where the typo is? I don't see where, as the script doesn't define any device name...

**Comment by Agh42** [comment]
I basically had to change these lines from "3" to "p3":

![image](https://github.com/schm1d/AwesomeArchLinux/assets/7584303/37e6ac4f-7cf7-4488-a491-393577e0da04)

**Comment by schm1d** [comment]
I see. I will fix that.
Thanks!

**Comment by schm1d** [comment]
Fixed
