### ISSUE TITLE
GRUB reporting unknown file system 

### ISSUE THREAD

**Issue by ghost** [schm1d/AwesomeArchLinux#2]
I am impressed by how thorough this secure installation is thus making it actually secure, but even with my tinkering I could not make it work.

The $DISK partitions could not be found at first, but I simply fixed that by adding an additional ‘p’ to every instance of $DISK “1/2/3” in archinstall.sh and chroot.sh as for me when the partitions are created, they are formatted as “p1/p2/p3”.

But now, grub-install refuses to install as every file system is unknown to it. I’ve tried commenting out the fstab mounting options, uncommenting the os prober in GRUB’s configuration file, running fsck, creating my own partitions with fdisk, generating a new grub.cfg, fstab, and mkinitcpio.conf.

I suppose I could just use systemd, but my only experience with Linux has been this one and I struggle with that one :)

**Comment by schm1d** [comment]
Can you post a screenshot of the error?

**Comment by ghost** [comment]
There are still two disk partition labels to fix in archinstall.sh, and one in chroot.sh. Since I do not have the indexes, use a search function.

After quickly fixing the git clone from the above, I ran it as instructed on a fresh, newly-updated live Arch Installation device.

Here are two “screenshots” you can take a look at. Keep in mind that even if the EFI partition (nvme0n1p2) is mounted to /mnt/efi and formatted as vfat (as well as having fsck run on it), it will still be read as an unknown file system. Perhaps mounting it to /mnt/boot/efi will fix this. Will keep experimenting.
![IMG_4653](https://github.com/schm1d/AwesomeArchLinux/assets/151401991/eefa4c4d-0a33-4cd3-86f7-5e1b70a1e89f)
![IMG_4656](https://github.com/schm1d/AwesomeArchLinux/assets/151401991/83816f2c-0e82-4fb3-ad88-8a611fd771a7)

**Comment by schm1d** [comment]
Hi, and sorry for the significantly delayed feedback on this:

The script is trying to install Grub from _chroot_.
I need to change the script to install Grub after exiting the chroot environment. 

I will update here as soon I test it.
Regards.

**Comment by schm1d** [comment]
I am closing this issue because it's now fixed on the new release.
